#  Probe Makefile for Mac OS X 10.8.x (Mountain Lion).
#  Uses 10.8 SDK with compiler flag declaring exec to be backward compatible
#  to Mac OS X 10.6 (Snow Leopard); -mmacosx-version-min=10.6
#  Either (or both) Intel architecture flags can be used: -arch i386 to create
#  a 32bit MACH-O exec, -arch x86_64 to create a 64bit MACH-O exec.

#  Either copy the Makefile.macOSX to Makefile to run the standard make command;
#  or use 'make -f Makefile.macOSX'.

MIN_OS      = -mmacosx-version-min=10.6
SDK_HOME    = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk
MACHINEFLAGS = -arch x86_64
CFLAGS = -isysroot $(SDK_HOME) $(MACHINEFLAGS) $(MIN_OS)
LFLAGS = -lm -Wl,-syslibroot,$(SDK_HOME) $(MACHINEFLAGS) $(MIN_OS)
OBJLIST = dots.o select.o readPDBrecs.o geom3d.o  stdconntable.o \
          abin.o parse.o  atomprops.o   utility.o autobondrot.o  \
          hybrid_36_c.o

.c.o:
	cc -c $*.c $(CFLAGS)

probe: probe.o $(OBJLIST)
	cc -o $@ probe.o $(OBJLIST) $(LFLAGS)

clean:
	@rm -f *.o *.ckp

install: probe
	mv probe /usr/local/bin

installtest: probe
	mv probe /usr/local/bin/probeTest

# DO NOT DELETE THIS LINE -- make depend uses it
abin.o:          ./abin.h  ./geom3d.h  ./utility.h  abin.c
atomprops.o:     ./atomprops.h  atomprops.c
autobondrot.o:   ./abin.h  ./autobondrot.h  ./geom3d.h  ./readPDBrecs.h \
                 ./utility.h  autobondrot.c
dots.o:          ./dots.h  ./geom3d.h  dots.c
geom3d.o:        ./geom3d.h  geom3d.c
parse.o:         ./parse.h  ./utility.h  parse.c
probe.o:         ./abin.h  ./atomprops.h  ./autobondrot.h  ./dots.h  ./geom3d.h \
                 ./parse.h  ./probe.h  ./readPDBrecs.h  ./select.h \
                 ./stdconntable.h  ./utility.h  probe.c
readPDBrecs.o:   ./geom3d.h  ./readPDBrecs.h  ./utility.h  readPDBrecs.c
select.o:        ./abin.h  ./atomprops.h  ./geom3d.h  ./parse.h  ./select.h \
                 ./stdconntable.h  ./utility.h  select.c
stdconntable.o:  ./stdconntable.h  stdconntable.c
utility.o:       utility.c
hybrid_36_c.o:  ./hybrid_36_c.h hybrid_36_c.c
# DO NOT DELETE THIS 2nd LINE -- make depend uses it
